### ISSUE TITLE
Usage without python-lsp-server

### ISSUE THREAD

**Issue by WhyNotHugo** [python-lsp/python-lsp-black#16]
Is it possible to use `python-lsp-black` without `python-lsp-server`? 

I'm using `jedi-language-server` instead of `python-lsp-server`, since the former fits my needs a lot better.
Can this LSP be used by itself without `python-lsp-server`

**Comment by ccordoba12** [comment]
Hey @WhyNotHugo, thanks for reporting. I have a couple of comments for you:

> Is it possible to use python-lsp-black without python-lsp-server?

No, it's not. This is not an LSP server, it's a plugin for the language server provided by `python-lsp-server`.

> since the former fits my needs a lot better.

Could explain why is that the case? Just curious and I'd like to learn more about `jedi-language-server`

> Can this LSP be used by itself without python-lsp-server

Well, as its name implies `jedi-language-server` only wraps those features that can be provided by Jedi in a language server (e.g. code completion and go-to-definition). Others, such as code formatting, are out of the scope (as far as I understand).

**Comment by WhyNotHugo** [comment]
Well, I use `jedi-language-server` and [`efm-langserver`](https://github.com/mattn/efm-langserver/) for python.

The former provides pretty good completion, code navigation (e.g.: "go to definition" or "find references"). It fulfils this role very well, at least for me.

The latter can wraps around tools like `black`, `flake8`(+plugins), `isort` and `mypy`, exposing them as LSPs (which provides a lot of error checking / linting / formatting, etc ([my neovim config for it](https://git.sr.ht/~whynothugo/dotfiles/tree/ff4d99b0/item/home/.config/nvim/lua/efm.lua)).

`python-language-server` doesn't really fit anywhere: it uses its own formatting style rather than black, and its linting gives me a lot of errors that are either not-an-issue in my case[1], false positives, or practices I don't follow[2]. The rest of its features overlap with other tools (e.g.: mypy, flake8), so I don't need them.

[1]: e.g.: `Variable name "e" doesn't conform to snake_case naming style`.
[2]: e.g.: `Too many instance attributes`

The python ecosystem in general has a bit too much of this: multiple tools where 70% of the features are shared, and the other 30% conflict in some way (e.g.: black vs yapf). So you either pick one or the other, but not both.

---

Site note: I realise you clearly use python-language-server, so take this as an opinionated explanation of why I prefer one vs the other, not a criticism of your choice.

**Comment by doolio** [comment]
> `python-language-server` doesn't really fit anywhere: it uses its own formatting style rather than black, and its linting gives me a lot of errors that are either not-an-issue in my case[1], false positives, or practices I don't follow[2]. The rest of its features overlap with other tools (e.g.: mypy, flake8), so I don't need them.

I think you are misunderstanding how the `python-lsp-server` works (or maybe language servers in general). It integrates different python tools behind a common interface that different clients can communicate with using a common protocol. It has built-in support for some of these tools (`pycodestyle`, `flake8` etc.) but some are supported via third party plugins (e.g. `python-lsp-black` though it is actually managed under the same github org but was originally developed independently, is a plugin that allows one to use `black`). By default for formatting it uses `autopep8` but one could use `yapf` or `black` if they prefer. I use `black` myself. The language server itself is not providing any of the analysis rather the underlying tools are so when you state it gives you a lot of false positives or practices you don't follow it is the underlying tool that is reporting these errors. You just need to configure them as you normally do or via the `workspace/didChangeConfiguration` method provided by the language server.

Therefore, to use all the tools you mention and only use one language server namely `python-lsp-server`:

```
$ python3 -m pip install "python-lsp-server[all]"
$ python3 -m pip install "python-lsp-black"
$ python3 -m pip install "pylsp-mypy"
$ python3 -m pip install "pyls-isort" 
```

`python-lsp-server` installs `jedi` by default so you get all the completions, definitions, hover, references, signature help, and symbols you are used to. Alternatively, you can use `rope` to provide such features if you prefer.

Instead of `python3 -m pip install "python-lsp-server[all]"` you can specify only a subset of the optional dependencies (see the [README](https://github.com/python-lsp/python-lsp-server)) for example to not install `autopep8` or `yapf` at all with something like `python3 -m pip install "python-lsp-server[pyflakes,mccabe,pycodestyle,pydocstyle,flake8]".

In any case `python-lsp-black` will use `black` and disable `autopep8` and 'yapf` by default if they are installed.

**Comment by WhyNotHugo** [comment]
Thanks for the explanation at the time. It was very useful, but I forgot to reply.

Indeed, python-lsp-server is a bit of a snowflake in its design. Usually, one just has multiple LSPs; one per underlying tool. I guess `python-lsp-server` has the upside of sharing a lot of the work across plugins.

**Comment by doolio** [comment]
> Usually, one just has multiple LSPs; one per underlying tool

Is that really the case (I'm unfamiliar with other languages)? Seems like a massive overhead which kind of defeats the purpose of the language server protocol.

**Comment by WhyNotHugo** [comment]
> Seems like a massive overhead which kind of defeats the purpose of the language server protocol.

The whole purpose of the language server protocol is to have a common API between IDEs and the tools that do checking/linting/etc.

It's an interesting idea to have "_a single LS per language with every tool as a separate plugin_", but that's definitely not part of the goal of LSPs nor a common approach.

Even now, I'm using python-lsp-server (for black and mypy) alongside ruff-lsp for Python (e.g.: two language servers). I don't know of any other LSP implemented in the same fashion as python-lsp-server.

**Comment by doolio** [comment]
> but that's definitely not part of the goal of LSPs nor a common approach.

I see. TIL. Thank you. I've only used this language server so far.
